'use strict';

const paths = {
  plane: '<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',
  home: '<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',
  compass: '<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5Z"/>',
  tag: '<path d="M20 13 11 22 2 13V3h10Z"/><circle cx="7" cy="8" r="1"/>',
  heart: '<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
  bag: '<rect x="3" y="6" width="18" height="15" rx="3"/><path d="M8 6V3h8v3M8 10v7m8-7v7"/>',
  moon: '<path d="M21 13A9 9 0 0 1 11 3a9 9 0 1 0 10 10Z"/>',
  sun: '<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',
  globe: '<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
  hotel: '<path d="M4 21V3h16v18M2 21h20M9 21v-5h6v5M8 7h1m6 0h1M8 11h1m6 0h1"/>',
  car: '<path d="m5 6-2 6v7h3v-3h12v3h3v-7l-2-6ZM3 12h18M7 6l1-3h8l1 3"/><path d="M6 14h2m8 0h2"/>',
  bundle: '<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M3 11h18M12 7v14M12 7C4 7 5 1 8 2c3 0 4 5 4 5Zm0 0c8 0 7-6 4-5-3 0-4 5-4 5Z"/>',
  pin: '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
  calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/>',
  users: '<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m2-17a3 3 0 0 1 0 6m2 11v-3a5 5 0 0 0-2-4"/>',
  search: '<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',
  arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  shield: '<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6Z"/><path d="m8 12 3 3 5-6"/>',
  sparkles: '<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',
  bolt: '<path d="m13 2-9 12h7l-1 8 10-13h-7Z"/>',
  camera: '<rect x="2" y="6" width="20" height="15" rx="3"/><path d="m7 6 2-3h6l2 3"/><circle cx="12" cy="13" r="4"/>',
  comment: '<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-3 3V11.5A8.5 8.5 0 0 1 9.5 3h3a8.5 8.5 0 0 1 8.5 8.5Z"/><path d="M7 9h8M7 13h5"/>',
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.compass}</svg>`;
const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const photo = (id, width = 800) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const photos = {
  mountain: photo('photo-1464822759023-fed622ff2c3b', 1800),
  pokhara: photo('photo-1544735716-392fe2489ffa'),
  kathmandu: photo('photo-1605640840605-14ac1855827b'),
  jaipur: photo('photo-1599661046827-dacff0c0f09a'),
  goa: photo('photo-1512343879784-a960bf40e7f2'),
  hotel1: photo('photo-1542314831-068cd1dbfeeb'),
  hotel2: photo('photo-1571896349842-33c89424de2d'),
  hotel3: photo('photo-1566073771259-6a8506099945'),
  room: photo('photo-1611892440504-42a792e24d32'),
  delhi: photo('photo-1587474260584-136574528ed5'),
  car: photo('photo-1503376780353-7e6692767b70'),
};
const destinations = [
  {city:'Pokhara', country:'Nepal', image:photos.pokhara, label:'A LITTLE PEACE', description:'Lakeside days. Mountain mornings.', stays:124},
  {city:'Kathmandu', country:'Nepal', image:photos.kathmandu, label:'CULTURE CALLING', description:'Old stories. New discoveries.', stays:286},
  {city:'Jaipur', country:'India', image:photos.jaipur, label:'THE PINK CITY', description:'A little color goes a long way.', stays:218},
  {city:'Goa', country:'India', image:photos.goa, label:'SLOW DOWN', description:'Sunshine, with a side of sea.', stays:342},
];
const inventory = [
  {id:'h1',type:'Hotels',name:'The Pavilions Himalayas',city:'Pokhara',country:'Nepal',price:6200,old:8500,rating:9.2,image:photos.hotel1,features:'Mountain views · Breakfast included',badge:'27% OFF', refundable:true},
  {id:'h2',type:'Hotels',name:'Dwarika’s Hotel',city:'Kathmandu',country:'Nepal',price:12800,old:16000,rating:9.6,image:photos.hotel2,features:'Heritage stay · Pool · Breakfast',badge:'A LITTLE LUXURY', refundable:true},
  {id:'h3',type:'Hotels',name:'Alila Diwa Goa',city:'Goa',country:'India',price:11360,old:15040,rating:9.1,image:photos.hotel3,features:'Infinity pool · Close to the beach',badge:'25% OFF', refundable:true},
  {id:'h4',type:'Hotels',name:'Jaipur Marriott',city:'Jaipur',country:'India',price:11360,old:15040,rating:8.9,image:photos.room,features:'City stay · Pool · Free Wi-Fi',badge:'GREAT VALUE', refundable:false},
  {id:'h5',type:'Hotels',name:'Lakeside Retreat',city:'Pokhara',country:'Nepal',price:4200,old:5800,rating:8.7,image:photos.hotel3,features:'Lake views · Free Wi-Fi · Breakfast',badge:'28% OFF', refundable:true},
  {id:'h6',type:'Hotels',name:'4-star mystery stay',city:'Kathmandu',country:'Nepal',price:5900,old:9000,rating:8.5,image:photos.room,features:'Thamel area · Free Wi-Fi · Name revealed after booking',badge:'EXPRESS DEAL',refundable:false,express:true,reveal:'Thamel Garden Hotel'},
  {id:'h7',type:'Hotels',name:'The Delhi Courtyard',city:'Delhi',country:'India',price:8800,old:12000,rating:8.8,image:photos.hotel1,features:'Central location · Breakfast included',badge:'27% OFF',refundable:true},
  {id:'f1',type:'Flights',name:'Kathmandu → Delhi',city:'Delhi',origin:'Kathmandu',country:'India',price:14500,old:18000,rating:9.0,image:photos.delhi,features:'10:30–12:10 · Nonstop · Economy · 20 kg baggage',badge:'NONSTOP',refundable:false},
  {id:'f2',type:'Flights',name:'Kathmandu → Pokhara',city:'Pokhara',origin:'Kathmandu',country:'Nepal',price:4800,old:6500,rating:8.8,image:photos.pokhara,features:'08:00–08:30 · Nonstop · Economy · 15 kg baggage',badge:'30 MINUTES AWAY',refundable:true},
  {id:'f3',type:'Flights',name:'Delhi → Kathmandu',city:'Kathmandu',origin:'Delhi',country:'Nepal',price:13600,old:17000,rating:8.9,image:photos.kathmandu,features:'13:00–15:00 · Nonstop · Economy · 20 kg baggage',badge:'NONSTOP',refundable:false},
  {id:'c1',type:'Cars',name:'Compact city car',city:'Kathmandu',country:'Nepal',price:3800,old:4500,rating:8.8,image:photos.car,features:'4 seats · Automatic · Airport pickup',badge:'CITY EXPLORER',refundable:true},
  {id:'c2',type:'Cars',name:'Comfort SUV',city:'Pokhara',country:'Nepal',price:6400,old:8000,rating:9.1,image:photos.car,features:'5 seats · Automatic · Lakeside pickup',badge:'ROOM TO EXPLORE',refundable:true},
  {id:'b1',type:'Bundles',name:'A little escape to Pokhara',city:'Pokhara',origin:'Kathmandu',country:'Nepal',price:24900,old:32500,rating:9.2,image:photos.pokhara,features:'Return flight from Kathmandu + 3 hotel nights · Per person',badge:'FLIGHT + HOTEL',refundable:false},
  {id:'b2',type:'Bundles',name:'Three sunny nights in Goa',city:'Goa',origin:'Delhi',country:'India',price:35200,old:44000,rating:9.0,image:photos.goa,features:'Return flight from Delhi + 3 hotel nights · Per person',badge:'FLIGHT + HOTEL',refundable:false},
];
const picks = [
  {id:'p1',city:'Pokhara',title:'The kind of sunset you stay for.',image:photos.pokhara,author:'Aarav S.',initials:'AS',location:'Phewa Lake, Pokhara',caption:'Find a quiet spot by the lake, order a chai, and let the mountains do their thing.',tag:'Nature · Budget',about:'Slow afternoons on the lakeside are the whole point. This sample traveler pick suggests finding a quiet café before sunset and taking time to explore on foot.'},
  {id:'p2',city:'Jaipur',title:'A pink city, a thousand stories.',image:photos.jaipur,author:'Meera K.',initials:'MK',location:'Old City, Jaipur',caption:'Early mornings in the old city hit different. Leave a little room for getting lost.',tag:'Culture · Solo travel',about:'A sample recommendation for a slow morning among Jaipur’s colorful streets. Start early, wander the old city, and leave time for a relaxed breakfast.'},
  {id:'p3',city:'Kathmandu',title:'Take the scenic way home.',image:photos.kathmandu,author:'Nima T.',initials:'NT',location:'Boudhanath, Kathmandu',caption:'One more turn, one more courtyard. Kathmandu always has something up its sleeve.',tag:'Culture · Friends',about:'Explore courtyards, local cafés, and the streets around Boudhanath. This illustrative pick celebrates the little discoveries between the main sights.'},
];
function readStore(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
const state = {page:'home',type:'Hotels',city:'',origin:'Kathmandu',start:'2026-10-20',end:'2026-10-23',travelers:2,country:'All',sort:'best',max:100000,refundable:false,express:false,saved:readStore('triply-saved',[]),trips:readStore('triply-trips',[]),currency:readStore('triply-currency','USD'),dark:readStore('triply-dark',false)};
if(!Array.isArray(state.saved))state.saved=[];
if(!Array.isArray(state.trips))state.trips=[];
const main=document.getElementById('main');
const modal=document.getElementById('modal');
let checkout=null;
let toastTimer;
function persist(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{toast('Your browser could not save this change.');}}
function money(amount){return TriplyTravel.formatMoney(amount,state.currency);}
function unit(item){return {Hotels:'/ night',Flights:'/ person',Cars:'/ day',Bundles:'/ person'}[item.type];}
function dateLabel(date){return new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'});}
function nights(start=state.start,end=state.end){return Math.max(1,Math.round((new Date(end+'T12:00:00')-new Date(start+'T12:00:00'))/86400000));}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
function nav(){document.getElementById('main-nav').innerHTML=[['home','home','Explore'],['picks','compass','Local Picks'],['deals','tag','Best Deals'],['saved','heart','Saved'],['trips','bag','My Trips']].map(([page,ic,label])=>`<a class="nav-link ${state.page===page?'active':''}" ${state.page===page?'aria-current="page"':''} href="#${page}">${icon(ic)}<span>${label}</span>${page==='saved'&&state.saved.length?`<span class="nav-count">${state.saved.length}</span>`:''}</a>`).join('');}
function savedButton(id){const saved=state.saved.includes(id);return `<button class="save-button ${saved?'saved':''}" data-action="save" data-id="${id}" aria-label="${saved?'Unsave':'Save'} ${esc(inventory.find(x=>x.id===id)?.name||picks.find(x=>x.id===id)?.title||'item')}" aria-pressed="${saved}">${icon('heart')}</button>`;}
function dealCard(item){const provider=TriplyTravel.bookingDestination(item,state);return `<article class="deal-card"><div class="deal-image-wrap"><button class="deal-photo-button" data-action="book" data-id="${item.id}" aria-label="View ${esc(item.name)}"><img src="${item.image}" alt="${item.express?'Illustrative hotel room':esc(item.city)+' travel inspiration'}" loading="lazy"></button><span class="deal-tag">SAMPLE · ${item.badge}</span>${savedButton(item.id)}</div><div class="deal-body"><div class="deal-location">${icon('pin')}${item.city}, ${item.country}</div><div class="deal-title-line"><h3><button class="deal-name-button" data-action="book" data-id="${item.id}">${item.name}</button></h3><span class="rating">★ ${item.rating.toFixed(1)}</span></div><p class="deal-amenities">${item.features}</p><div class="deal-price-line"><div><span class="price-original">${money(item.old)}</span><br><span class="price">${money(item.price)}</span><span class="price-unit">${unit(item)}</span><div class="savings">Sample savings ${money(item.old-item.price)}</div></div><button class="deal-book deal-website-button" data-action="book" data-id="${item.id}" aria-label="View deal for ${esc(item.name)}">View deal ↗</button></div><div class="provider-caption">Check live availability on ${provider.name}</div></div></article>`;}
function pickCard(item){return `<article class="pick-card"><div class="pick-image"><img src="${item.image}" alt="${item.location}" loading="lazy">${savedButton(item.id)}<span class="verified-badge">${icon('shield')}Verified Trip · Sample</span></div><div class="pick-body"><div class="pick-author"><span class="small-avatar">${item.initials}</span><strong>${item.author}</strong><span>in ${item.city}</span></div><h3>${item.title}</h3><p>${item.caption}</p><div class="pick-bottom"><span>${item.tag}</span><button class="text-link" data-action="place" data-id="${item.id}">Take a look ${icon('arrow')}</button></div><div class="pick-discussion"><button class="comment-link" data-action="comments" data-id="${item.id}" aria-label="${commentCount(item.id)} comments on ${esc(item.title)}">${icon('comment')}<span>${commentCount(item.id)} comments</span><span class="join-label">Join the conversation</span></button><div class="quick-questions">${questionChips(item.id)}</div></div></div></article>`;}
function heading(title,description,right=''){return `<div class="section-heading"><div><h2>${title}</h2><p>${description}</p></div>${right}</div>`;}
function empty(title,description,button='Explore destinations',target='home'){return `<div class="empty-state">${icon('compass')}<h2>${title}</h2><p>${description}</p><a href="#${target}" class="primary-button">${button}${icon('arrow')}</a></div>`;}
function searchForm(inResults=false){return `<form id="search-form" class="search-card ${inResults?'results-search':''}"><div class="search-tabs" role="tablist" aria-label="Travel category">${[['Hotels','hotel'],['Flights','plane'],['Cars','car'],['Bundles','bundle']].map(([name,ic])=>`<button type="button" role="tab" aria-selected="${state.type===name}" class="search-tab ${state.type===name?'active':''}" data-action="type" data-type="${name}">${icon(ic)}${name}</button>`).join('')}</div><div class="search-fields">${state.type==='Flights'||state.type==='Bundles'?`<label class="field">${icon('plane')}<div class="field-content"><span class="field-label">DEPARTING FROM</span><select name="origin"><option ${state.origin==='Kathmandu'?'selected':''}>Kathmandu</option><option ${state.origin==='Delhi'?'selected':''}>Delhi</option></select></div></label>`:''}<label class="field">${icon('pin')}<div class="field-content"><span class="field-label">${state.type==='Cars'?'PICKUP LOCATION':'WHERE TO?'}</span><select name="city" aria-label="Destination"><option value="">Anywhere in Nepal & India</option>${['Pokhara','Kathmandu','Jaipur','Goa','Delhi'].map(city=>`<option ${state.city===city?'selected':''}>${city}</option>`).join('')}</select></div></label><div class="field">${icon('calendar')}<div class="field-content"><span class="field-label">${state.type==='Flights'?'DEPARTURE · ONE WAY':'YOUR DATES'}</span><div class="date-inputs"><input aria-label="Start date" type="date" name="start" min="2026-10-03" value="${state.start}" required>${state.type==='Flights'?'':`<span>—</span><input aria-label="End date" type="date" name="end" min="${state.start}" value="${state.end}" required>`}</div></div></div><label class="field">${icon('users')}<div class="field-content"><span class="field-label">${state.type==='Hotels'?'GUESTS · 1 ROOM':'TRAVELERS'}</span><select name="travelers">${[1,2,3,4].map(n=>`<option value="${n}" ${state.travelers===n?'selected':''}>${n} adult${n>1?'s':''}</option>`).join('')}</select></div></label><button class="primary-button" type="submit">${icon('search')}Search deals</button></div><div id="search-error" class="search-error" role="alert"></div></form>`;}
function countrySwitch(){return `<div class="country-switch" aria-label="Destination country">${['All','Nepal','India'].map(country=>`<button data-action="country" data-country="${country}" class="${state.country===country?'active':''}" aria-pressed="${state.country===country}">${country}</button>`).join('')}</div>`;}
function home(){return `<div class="page-intro"><div><h1>A little escape looks good on you.</h1><p>Your next great story starts somewhere new.</p></div><div class="weather">${icon('sun')}<div><strong>Less rush. More wonder.</strong><br>Nepal & India are calling.</div></div></div><section class="hero" aria-label="Discover Nepal and India"><img src="${photos.mountain}" alt="Sunlit mountain peaks above a green alpine valley" fetchpriority="high"><div class="hero-content"><div class="hero-tag">CLOSER TO THE PLACES YOU LOVE</div><h2>Go somewhere<br>that <em>stays with you.</em></h2><p>From Himalayan mornings to coastal sunsets.<br>Find your kind of escape, for a little less.</p></div><div class="hero-location">${icon('pin')}A little mountain inspiration</div></section>${searchForm()}<div class="trust-row"><span>${icon('tag')}Good deals, without the guesswork</span><span>${icon('shield')}Clear prices, easy choices</span><span>${icon('heart')}Made for Nepal & India</span></div><section>${heading('Where to next?','A few places we can’t stop thinking about.',countrySwitch())}<div class="destinations-grid">${destinations.filter(d=>state.country==='All'||d.country===state.country).map(d=>`<button class="destination-card" data-action="destination" data-city="${d.city}"><img src="${d.image}" alt="${d.city}, ${d.country}" loading="lazy"><span class="destination-tag">${d.label}</span><div class="destination-copy"><h3>${d.city}</h3><p>${d.country} · Find your stay</p><span class="destination-arrow">↗</span></div></button>`).join('')}</div></section><section class="content-section">${heading('Good trips. Even better prices.','A little less on your stay. A little more for the journey.',`<a href="#deals" class="text-link">View all deals ${icon('arrow')}</a>`)}<div class="deals-grid">${inventory.slice(0,3).map(dealCard).join('')}</div></section><section class="express-banner"><div class="express-symbol">${icon('bolt')}</div><div><div class="eyebrow">A LITTLE MYSTERY. A LOT OF SAVINGS.</div><h3>Meet your next happy surprise.</h3><p>Know the neighborhood. Love the price. Reveal the hotel after booking.</p></div><button class="text-link" data-action="express">Explore Express Deals ${icon('arrow')}</button></section><section class="content-section">${heading('Good places. Real perspectives.','A little inspiration from the people who’ve been there.',`<a href="#picks" class="text-link">Explore Local Picks ${icon('arrow')}</a>`)}<div class="picks-grid">${picks.map(pickCard).join('')}</div></section><p class="demo-note">A prototype made for exploring. Listings, prices, ratings, traveler stories, and bookings are illustrative. Photography shows travel inspiration, not verified properties.</p>`;}
function results(){let items=inventory.filter(item=>item.type===state.type&&(!state.city||item.city===state.city)&&(!item.origin||item.origin===state.origin)&&item.price<=state.max&&(!state.refundable||item.refundable)&&(!state.express||item.express));items.sort(state.sort==='price'?(a,b)=>a.price-b.price:state.sort==='rating'?(a,b)=>b.rating-a.rating:(a,b)=>(b.old-b.price)/b.old-(a.old-a.price)/a.old);return `<div class="page-intro"><div><h1>${state.express?'A little mystery. A better deal.':state.city?`Find your ${state.city} escape.`:'Your next escape, for a little less.'}</h1><p>${state.express?'The area, amenities, and conditions are upfront. The hotel name is the surprise.':'Compare a few good options. Make room for a great trip.'}</p></div></div>${searchForm(true)}<div class="filterbar"><button class="filter-chip ${state.refundable?'active':''}" data-action="refundable" aria-pressed="${state.refundable}">Free cancellation</button>${state.type==='Hotels'?`<button class="filter-chip ${state.express?'active':''}" data-action="express-filter" aria-pressed="${state.express}">Express Deals</button>`:''}<label>Budget <select id="budget-filter" aria-label="Maximum unit price">${[100000,6000,10000,15000].map(n=>`<option value="${n}" ${state.max===n?'selected':''}>${n===100000?'Any price':`Under ${money(n)}`}</option>`).join('')}</select></label><label class="sort">Sort by <select id="sort-filter"><option value="best" ${state.sort==='best'?'selected':''}>Best savings</option><option value="price" ${state.sort==='price'?'selected':''}>Lowest price</option><option value="rating" ${state.sort==='rating'?'selected':''}>Top rated</option></select></label></div><p class="results-count">${items.length} demo ${state.type.toLowerCase()} ${state.city?'in '+state.city:'across Nepal & India'} · ${dateLabel(state.start)}${state.type==='Flights'?'':' – '+dateLabel(state.end)} · ${state.travelers} adult${state.travelers>1?'s':''}</p>${items.length?`<div class="deals-grid">${items.map(dealCard).join('')}</div>`:`<div class="empty-state">${icon('search')}<h2>No matches this time.</h2><p>Try another destination, a higher budget, or fewer filters.</p><button data-action="reset-filters" class="primary-button">Reset search</button></div>`}<p class="demo-note">Illustrative prices, not live offers. Check availability, total cost, and cancellation terms on the booking website. Demo conversions: USD 1 = NPR 135; INR 1 = NPR 1.60. Hotels are per room; flights and bundles are per person.</p>`;}
function localPicks(){return `<div class="page-intro"><div><h1>A good trip is worth sharing.</h1><p>Small discoveries. Useful tips. Your next “let’s go there.”</p></div><button class="primary-button" data-action="share">${icon('camera')}Share a pick</button></div><div class="filterbar">${countrySwitch()}</div><div class="picks-grid">${picks.filter(p=>state.country==='All'||destinations.find(d=>d.city===p.city)?.country===state.country).map(pickCard).join('')}</div><section class="express-banner"><div class="express-symbol">${icon('shield')}</div><div><div class="eyebrow">A LITTLE MORE TRUST</div><h3>Real journeys make the best recommendations.</h3><p>Posting unlocks after an eligible completed trip. Demo bookings do not grant verification.</p></div></section><p class="demo-note">These are sample stories and verification badges to demonstrate the Local Picks experience.</p>`;}
function saved(){const hotels=inventory.filter(i=>state.saved.includes(i.id));const places=picks.filter(i=>state.saved.includes(i.id));return `<div class="page-intro"><div><h1>For your someday-soon list.</h1><p>Good places and good deals. Right here when you’re ready.</p></div></div>${!hotels.length&&!places.length?empty('A little inspiration belongs here.','Tap the heart on a deal or a Local Pick to save it for later.'):''}${hotels.length?`<section>${heading('Your saved deals',`${hotels.length} reason${hotels.length>1?'s':''} to get away.`)}<div class="deals-grid">${hotels.map(dealCard).join('')}</div></section>`:''}${places.length?`<section class="content-section">${heading('Places on your mind','Keep the inspiration close.')}<div class="picks-grid">${places.map(pickCard).join('')}</div></section>`:''}`;}
function trips(){return `<div class="page-intro"><div><h1>Your next chapter is out there.</h1><p>Your plans, neatly in one place.</p></div></div>${!state.trips.length?empty('Your journey starts here.','Browse deals and book on the provider’s website. Keep your booking confirmation from that provider.'):state.trips.map(trip=>`<article class="trip-card"><img src="${trip.image}" alt="Travel inspiration for ${esc(trip.city)}"><div><span class="trip-status">✓ DEMO CONFIRMED</span><h3>${esc(trip.name)}</h3><p>${esc(trip.city)} · ${esc(trip.type)}<br>${dateLabel(trip.start)}${trip.type==='Flights'?'':' – '+dateLabel(trip.end)} · ${trip.travelers} adult${trip.travelers>1?'s':''}<br>Reference: ${esc(trip.reference)}</p></div><div class="trip-total"><strong>${money(trip.total)}</strong><small>Simulated total · No charge</small><br><button class="text-link" style="margin-top:12px" data-action="confirmation" data-id="${trip.reference}">View confirmation ${icon('arrow')}</button></div></article>`).join('')}<p class="demo-note">Earlier demo bookings are stored in this browser only. New bookings are completed on external websites and do not sync to My Trips.</p>`;}
function render(){nav();main.innerHTML=({home,picks:localPicks,deals:results,saved,trips}[state.page]||home)();hydrateIcons();}
function hydrateIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
function navigate(page){if(location.hash==='#'+page){state.page=page;render();window.scrollTo({top:0,behavior:'smooth'});}else location.hash=page;}
function captureSearch(){const form=document.getElementById('search-form');if(!form)return;const data=new FormData(form);state.city=data.get('city')||'';state.origin=data.get('origin')||state.origin;state.start=data.get('start')||state.start;state.end=data.get('end')||state.end;state.travelers=Number(data.get('travelers'))||2;}
function showModal(title,subtitle,body){modal.innerHTML=`<div class="modal-header"><div><h2 id="modal-title">${title}</h2><p>${subtitle}</p></div><button class="close-button" data-action="close" aria-label="Close dialog">×</button></div><div class="modal-body">${body}</div>`;if(!modal.open)modal.showModal();}
function openPlace(id){const p=picks.find(p=>p.id===id);showModal(p.location,'A Local Pick · Sample verified traveler story',`<img class="place-hero" src="${p.image}" alt="${p.location}"><div class="pick-author"><span class="small-avatar">${p.initials}</span><strong>${p.author}</strong><span>${p.tag}</span></div><h3 style="margin-bottom:12px">${p.title}</h3><p>${p.about}</p><div class="place-discussion"><button class="comment-link" data-action="comments" data-id="${p.id}">${icon('comment')}${commentCount(p.id)} comments · Ask the traveler ${icon('arrow')}</button></div><div class="modal-actions"><button class="secondary-button" data-action="save-place" data-id="${p.id}">${state.saved.includes(p.id)?'Saved to your list':'Save this place'}</button><button class="primary-button" data-action="nearby" data-city="${p.city}">Find nearby stays ${icon('arrow')}</button></div>`);}
function summary(item){return `<div class="booking-summary"><img src="${item.image}" alt="Illustrative ${item.city} travel photo"><div><h3>${item.name}</h3><p>${item.city}, ${item.country}<br>${dateLabel(state.start)}${item.type==='Flights'?'':' – '+dateLabel(state.end)} · ${state.travelers} adult${state.travelers>1?'s':''}</p></div></div>`;}
function openBookingWebsite(id){
  const item=inventory.find(i=>i.id===id);
  if(!item)return;
  captureSearch();
  if(item.type!=='Flights' && state.end<=state.start){toast('Choose an end date after your start date before continuing.');return;}
  const provider=TriplyTravel.bookingDestination(item,state);
  showModal(`Continue to ${provider.name}`,'CHECK LIVE PRICES · BOOK WITH THE PROVIDER',`${summary(item)}<div class="notice"><strong>Check the current price before booking.</strong><br>${esc(provider.note)}</div><div class="price-breakdown"><div><span>Triply sample price</span><strong>${money(item.price)} ${unit(item)}</strong></div><div><span>Travelers</span><span>${state.travelers} adults</span></div>${item.origin?`<div><span>Departing from</span><span>${esc(item.origin)}</span></div>`:''}</div><p class="demo-note">Opens a new tab. The provider handles availability, payment, confirmation, and cancellations. Prices shown in Triply are examples, not guaranteed offers.</p><div class="modal-actions"><button class="secondary-button" data-action="close">Keep browsing</button><a class="primary-button" href="${esc(provider.url)}" target="_blank" rel="noopener noreferrer">Continue to ${provider.name} ↗</a></div>`);
}
function totals(item){const quantity=item.type==='Hotels'||item.type==='Cars'?nights():state.travelers;return {quantity,total:item.price*quantity};}
function beginBooking(id){const item=inventory.find(i=>i.id===id);if(item.type==='Bundles'){const end=new Date(state.start+'T12:00:00');end.setDate(end.getDate()+3);state.end=end.toISOString().slice(0,10);}checkout={item,traveler:null,payment:'Demo card'};bookingStep1();}
function bookingStep1(){const item=checkout.item;showModal('Make room for your next adventure.','STEP 1 OF 2 · TRAVELER DETAILS',`${summary(item)}<form id="traveler-form"><div class="form-grid"><label class="form-label">First name<input name="first" autocomplete="given-name" required maxlength="50" value="${esc(checkout.traveler?.first||'')}"></label><label class="form-label">Last name<input name="last" autocomplete="family-name" required maxlength="50" value="${esc(checkout.traveler?.last||'')}"></label><label class="form-label full-width">Email address<input name="email" type="email" autocomplete="email" required maxlength="100" value="${esc(checkout.traveler?.email||'')}"></label><label class="form-label">Departure / check-in<input type="date" name="start" min="2026-10-03" value="${state.start}" required></label>${item.type==='Flights'?'':`<label class="form-label">${item.type==='Bundles'?'Return · 3 nights':'Return / check-out'}<input type="date" name="end" min="${state.start}" value="${state.end}" ${item.type==='Bundles'?'readonly':''} required></label>`}</div><p class="demo-note">Use sample details to explore. No information is sent to a booking or payment provider.</p><div class="search-error" id="booking-error" role="alert"></div><div class="modal-actions"><span class="deal-location">${icon('shield')} Your demo stays in this browser</span><button type="submit" class="primary-button">Review booking ${icon('arrow')}</button></div></form>`);}
function bookingStep2(){const item=checkout.item;const {quantity,total}=totals(item);const label=item.type==='Hotels'?`${quantity} night${quantity>1?'s':''} · 1 room`:item.type==='Cars'?`${quantity} rental day${quantity>1?'s':''}`:`${quantity} traveler${quantity>1?'s':''}`;showModal('One last look. Then you’re off.','STEP 2 OF 2 · REVIEW & SIMULATE PAYMENT',`${summary(item)}${item.express?'<div class="notice"><strong>Your mystery stay, clearly explained.</strong><br>4-star hotel in Thamel, Kathmandu · Sample guest rating 8.5+ · Free Wi-Fi. The hotel name is revealed after demo confirmation. This Express Deal is non-refundable and cannot be changed.</div>':`<div class="notice">${item.refundable?'Demo cancellation terms: full refund until 48 hours before the start date; non-refundable thereafter.':'Non-refundable demo rate. Changes and cancellations are not included.'}${item.type==='Bundles'?'<br>This bundle includes a return flight and exactly 3 hotel nights.':''}</div>`}<div class="price-breakdown"><div><span>${money(item.price)} × ${label}</span><span>${money(total)}</span></div><div><span>Taxes & fees</span><span>Included in demo rate</span></div><div class="total"><span>Total</span><span>${money(total)}</span></div></div><form id="payment-form"><span class="form-label">Choose a simulated payment method</span>${(item.country==='India'?['Demo UPI','Demo card']:['Demo wallet','Demo card']).map((p,i)=>`<label class="payment-choice"><input type="radio" name="payment" value="${p}" ${i===0?'checked':''}>${p}<span style="margin-left:auto;color:var(--muted);font-size:10px">No charge</span></label>`).join('')}<label class="check-label"><input name="terms" type="checkbox" required><span>I understand the ${item.refundable?'cancellation':'non-refundable'} conditions and that this is a simulated booking.</span></label><div class="modal-actions"><button type="button" class="secondary-button" data-action="booking-back">Back</button><button type="submit" class="primary-button">Confirm demo booking ${icon('arrow')}</button></div></form>`);}
function confirmBooking(payment){if(!checkout)return;const {item,traveler}=checkout;const trip={reference:'TRP-'+crypto.randomUUID().slice(0,8).toUpperCase(),id:item.id,name:item.reveal||item.name,image:item.image,city:item.city,type:item.type,start:state.start,end:state.end,travelers:state.travelers,total:totals(item).total,first:traveler.first,payment};state.trips.unshift(trip);persist('triply-trips',state.trips);checkout=null;showConfirmation(trip);render();}
function showConfirmation(trip){showModal('A little closer to your next trip.','DEMO BOOKING CONFIRMATION',`<div class="success-view"><div class="success-icon">${icon('check')}</div><h3>You’re all set, ${esc(trip.first)}.</h3><p>Your demo booking for <strong>${esc(trip.name)}</strong> is confirmed.<br>${esc(trip.city)} · ${dateLabel(trip.start)}${trip.type==='Flights'?'':' – '+dateLabel(trip.end)}</p><div class="confirmation-code">${esc(trip.reference)}</div><p>${money(trip.total)} · ${esc(trip.payment)}<br>No payment was charged and no reservation was made.<br>Your confirmation is saved in My Trips on this browser.</p><button class="primary-button" style="margin-top:22px" data-action="view-trips">View My Trips ${icon('arrow')}</button></div>`);}
function toggleSave(id){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];persist('triply-saved',state.saved);toast(state.saved.includes(id)?'A little inspiration, saved for later.':'Removed from your saved list.');render();}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el)return;const {action,id,city}=el.dataset;
  if(action==='save')toggleSave(id);
  if(action==='save-place'){toggleSave(id);el.textContent=state.saved.includes(id)?'Saved to your list':'Save this place';}
  if(action==='type'){captureSearch();state.type=el.dataset.type;state.express=false;render();}
  if(action==='country'){state.country=el.dataset.country;render();}
  if(action==='destination'||action==='nearby'){modal.close();state.city=city;state.type='Hotels';state.express=false;state.refundable=false;state.max=100000;navigate('deals');}
  if(action==='express'){state.city='';state.type='Hotels';state.express=true;state.refundable=false;state.max=100000;navigate('deals');}
  if(action==='express-filter'){captureSearch();state.express=!state.express;render();}
  if(action==='refundable'){captureSearch();state.refundable=!state.refundable;render();}
  if(action==='reset-filters'){state.city='';state.max=100000;state.refundable=false;state.express=false;state.origin='Kathmandu';render();}
  if(action==='place')openPlace(id);
  if(action==='book')openBookingWebsite(id);
  if(action==='close')modal.close();
  if(action==='booking-back')bookingStep1();
  if(action==='view-trips'){modal.close();navigate('trips');}
  if(action==='confirmation')showConfirmation(state.trips.find(t=>t.reference===id));
  if(action==='share')showModal('Good stories start with a real trip.','SHARE YOUR TRIP · POSTING LOCKED',`<div class="success-view"><div class="success-icon">${icon('shield')}</div><h3>Your first pick is worth the wait.</h3><p>Local Picks posting unlocks after an eligible completed booking. Your post will be connected to that trip to keep recommendations useful and credible.</p><div class="notice">This prototype uses simulated bookings, so it does not unlock verified posting. Browse and save the sample picks to explore the experience.</div><button class="primary-button" data-action="close">Keep exploring ${icon('arrow')}</button></div>`);
});
document.addEventListener('submit',event=>{if(event.target.id==='search-form'){event.preventDefault();captureSearch();if(state.type!=='Flights'&&state.end<=state.start){document.getElementById('search-error').textContent='Choose an end date after your start date.';return;}if((state.type==='Flights'||state.type==='Bundles')&&state.origin===state.city){document.getElementById('search-error').textContent='Choose different departure and destination cities.';return;}navigate('deals');}
  if(event.target.id==='traveler-form'){event.preventDefault();const data=new FormData(event.target);const start=data.get('start');let end=data.get('end')||state.end;if(checkout.item.type==='Bundles'){const date=new Date(start+'T12:00:00');date.setDate(date.getDate()+3);end=date.toISOString().slice(0,10);}if(checkout.item.type!=='Flights'&&end<=start){document.getElementById('booking-error').textContent='Choose an end date after your start date.';return;}if(!data.get('first').trim()||!data.get('last').trim()){document.getElementById('booking-error').textContent='Enter your first and last name.';return;}state.start=start;state.end=end;checkout.traveler={first:data.get('first').trim(),last:data.get('last').trim(),email:data.get('email')};bookingStep2();}
  if(event.target.id==='payment-form'){event.preventDefault();confirmBooking(new FormData(event.target).get('payment'));}
});
document.addEventListener('change',event=>{if(event.target.id==='budget-filter'){captureSearch();state.max=Number(event.target.value);render();}if(event.target.id==='sort-filter'){captureSearch();state.sort=event.target.value;render();}if(event.target.name==='start'){const endInput=event.target.form?.querySelector('[name="end"]');if(endInput)endInput.min=event.target.value;}});
document.getElementById('currency').value=state.currency;
document.getElementById('currency').addEventListener('change',event=>{state.currency=event.target.value;persist('triply-currency',state.currency);render();toast('Currency updated · Fixed demo conversion');});
document.getElementById('profile-button').addEventListener('click',()=>navigate('trips'));
function applyTheme(){document.documentElement.classList.toggle('dark',state.dark);document.getElementById('theme-toggle').setAttribute('aria-pressed',String(state.dark));}
document.getElementById('theme-toggle').addEventListener('click',()=>{state.dark=!state.dark;persist('triply-dark',state.dark);applyTheme();});
modal.addEventListener('click',event=>{if(event.target===modal){const box=modal.getBoundingClientRect();if(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)modal.close();}});
window.addEventListener('hashchange',()=>{state.page=location.hash.slice(1)||'home';if(!['home','deals','picks','saved','trips'].includes(state.page))state.page='home';render();window.scrollTo(0,0);});
state.page=['home','deals','picks','saved','trips'].includes(location.hash.slice(1))?location.hash.slice(1):'home';
applyTheme();render();
