const fs=require('node:fs'),path=require('node:path');
function createDiscovery({dataDir,fetchImpl=fetch}){
  const cache=new Map(),pending=new Map();let queue=Promise.resolve(),lastGeo=0;
  async function cached(key,ttl,load){const hit=cache.get(key);if(hit&&Date.now()-hit.at<ttl)return hit.value;if(pending.has(key))return pending.get(key);const promise=load().then(value=>{if(cache.size>300)cache.delete(cache.keys().next().value);cache.set(key,{at:Date.now(),value});return value;}).finally(()=>pending.delete(key));pending.set(key,promise);return promise;}
  async function json(url,options={}){const response=await fetchImpl(url,{headers:{'User-Agent':'Triply/2.0 (https://github.com/bibek061/triply)'},signal:AbortSignal.timeout(20000),...options});if(!response.ok)throw Error('External discovery service unavailable');return response.json();}
  async function places({country,location,category}){return cached(JSON.stringify([country,location.toLowerCase(),category]),3600000,async()=>{
    const job=queue.then(async()=>{await new Promise(resolve=>setTimeout(resolve,Math.max(0,1100-(Date.now()-lastGeo))));lastGeo=Date.now();return json(`https://nominatim.openstreetmap.org/search?${new URLSearchParams({q:location,countrycodes:country.toLowerCase(),format:'jsonv2',limit:'1'})}`);});queue=job.catch(()=>{});const centers=await job;if(!centers.length)return {places:[],center:null,message:'No location found in this country. Try a nearby town.'};const lat=Number(centers[0].lat),lon=Number(centers[0].lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error('Invalid coordinates');
    const selectors={camping:['nwr["tourism"="camp_site"]'],hiking:['relation["route"="hiking"]','nwr["natural"="peak"]'],views:['nwr["tourism"="viewpoint"]'],beaches:['nwr["natural"="beach"]'],attractions:['nwr["tourism"="attraction"]','nwr["historic"]']};const chosen=selectors[category]||Object.values(selectors).flat();const query=`[out:json][timeout:15];(${chosen.map(s=>`${s}["name"](around:20000,${lat},${lon});`).join('')});out center 35;`;
    const result=await json('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({data:query})});return {center:{lat,lon,name:centers[0].display_name},checkedAt:new Date().toISOString(),places:(result.elements||[]).map(p=>({id:`osm-${p.type}-${p.id}`,name:p.tags.name,category:p.tags.tourism==='camp_site'?'camping':p.tags.route==='hiking'||p.tags.natural==='peak'?'hiking':p.tags.tourism==='viewpoint'?'views':p.tags.natural==='beach'?'beaches':'attractions',detail:p.tags.description||p.tags.tourism||p.tags.natural||'Outdoor place',url:`https://www.openstreetmap.org/${p.type}/${p.id}`,fee:p.tags.fee==='yes'?'Admission may apply':p.tags.fee==='no'?'No fee listed':'Check access & fees'}))};
  });}
  async function convert(amount,from,to){if(from===to)return {amount,from,to,converted:amount};const file=path.join(dataDir,'exchange-cache.json');let stored;try{stored=JSON.parse(fs.readFileSync(file,'utf8'));}catch{}let data=stored;if(!data||Date.now()-data.fetchedAt>86400000)data=await cached('rates',86400000,async()=>{const value=await json('https://open.er-api.com/v6/latest/USD');if(value.result!=='success'||!value.rates?.USD)throw Error('Currency rates unavailable');const fresh={...value,fetchedAt:Date.now()};fs.writeFileSync(file,JSON.stringify(fresh));return fresh;}).catch(error=>{if(stored&&Date.now()-stored.fetchedAt<7*86400000)return stored;throw error;});if(!data.rates[from]||!data.rates[to])return {error:'This currency is not covered by the rate provider. No conversion was made.'};return {amount,from,to,converted:amount/data.rates[from]*data.rates[to],updatedAt:data.time_last_update_utc,stale:Date.now()-data.fetchedAt>86400000};}
  return {places,convert};
}module.exports={createDiscovery};
